name: deeprlbootcamp
channels:
  - defaults
dependencies:
  - python=3.5.3
  - opencv-python==3.4.1.15
  - scipy==1.1.0
  - pip:

    - gym==0.9.2
    - chainer==2.0.1
    - tblib==1.3.2
    - atari-py==0.1.1
    - pillow==5.2.0
    - pyopengl==3.1.0
    - cloudpickle==0.5.3
    - click==6.7
    - flask==1.0.2
    - plotly==3.0.2
    - tqdm==4.23.4  
    - chardet==3.0.4
    - cycler==0.10.0
    - filelock==3.0.4
    - future==0.16.0
    - idna==2.7
    - itsdangerous==0.24
    - matplotlib==2.0.2
    - nose==1.3.7
    - protobuf==3.6.0
    - pyglet==1.3.2
    - pyparsing==2.2.0
    - pytz==2018.5
    - requests==2.19.1
    - retrying==1.3.3
    - urllib3==1.23
    - werkzeug==0.14.1


